### ISSUE TITLE
Stuck at <waiting for any device>

### ISSUE THREAD

**Issue by Alumniminium** [konradybcio/pmms#1]
Telnet won't connect either. 
Modem seems to be working though, 4G came back online and I got a shell using adb
PP 1.2b, Arch

**Comment by konradybcio** [comment]
Hi!

Since 4G came back, the modem must have rebooted to the original OS...

Did you flash Biktor's modified LK (`fastboot flash:raw aboot prebuilts/emmc_appsboot.mbn`)?

Did you unlock the modem?

Did fastboot say "booting something (abcd KB)"?

Please provide more info, preferably including all the terminal logs and i will try to help you.

**Comment by Alumniminium** [comment]
```
*** local echo: yes ***
AT+QADBKEY?

+QADBKEY: 13609505

OK
AT+QADBKEY="tdxi83Zcy7JYo3N2"

OK
AT+QCFG="usbcfg",0x2C7C,0x125,1,1,1,1,1,1,0

OK

FATAL: read zero bytes from port
term_exitfunc: reset failed for dev UNKNOWN: Input/output error
```

```
➜  pmms git:(master) ✗ sudo ./qletsgo.sh 
Detected PinePhone version (1.2), using pin 68 as reset
< waiting for any device >
```

> Did you flash Biktor's modified LK (fastboot flash:raw aboot prebuilts/emmc_appsboot.mbn)?

no, where can I get more info on that?

**Comment by konradybcio** [comment]
Yeah so.. I forgot about a few steps.. I added them to README, could you try again?
